### ISSUE TITLE
Logins seem broken with email

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#668] opened 2015-03-17 22:31 UTC
renee+inca@spideroak.com with standard QA pass will log in online but not in mobile app. QAten with the same pass logs in fine.

**Comment by devgeeks** [comment] 2015-03-17 22:38
This smells of being caused by the switch away from `/browse` (much like the case sensitivity issue for usernames).

Can you confirm if it is login via email address that is the issue, or that email address specifically?

**Comment by reneelynn** [comment] 2015-03-17 22:39
It happens with other email-only test accounts.

**Comment by devgeeks** [comment] 2015-03-17 22:41
Yeah, I can't log in using my email address on my main account.

**Comment by kenmanheimer** [comment] 2015-03-19 22:14
Fixed by #669.

**Closed** 2015-03-19 22:17 UTC
Labels: 3 - Done, android, ios
